/* Elenco compiti 4ALL linguistico — estate 2026 + richieste dei prof */
function items(prefix, rows) {
  return rows.map((row) => {
    const [num, nick, req, files] = row;
    const first = String(req || nick).split("\n")[0];
    return {
      id: prefix + "-" + num,
      title: num + ". " + first,
      ...(req ? { req } : {}),
      ...(files ? { files } : {}),
    };
  });
}

const F = {
  itLetture: { name: "Letture estive quarta.pdf", href: "./file/it-letture-estive.pdf", from: "prof" },
  itTracce: { name: "P000_ORD25 — tracce maturità.pdf", href: "./file/it-tracce-maturita.pdf", from: "prof" },
  itPavese1: { name: "Pavese — Blocco 1 (cap. I–VI).pdf", href: "./file/it-pavese-blocco1.pdf", from: "ours" },
  itPavese2: { name: "Pavese — Blocco 2.pdf", href: "./file/it-pavese-blocco2.pdf", from: "ours" },
  itPavese3: { name: "Pavese — Blocco 3.pdf", href: "./file/it-pavese-blocco3.pdf", from: "ours" },
  itPavese4: { name: "Pavese — Blocco 4 (finale).pdf", href: "./file/it-pavese-blocco4.pdf", from: "ours" },
  itOrwell1: { name: "Orwell 1984 — Blocco 1.pdf", href: "./file/it-orwell-blocco1.pdf", from: "ours" },
  itOrwell2: { name: "Orwell 1984 — Blocco 2.pdf", href: "./file/it-orwell-blocco2.pdf", from: "ours" },
  itOrwell3: { name: "Orwell 1984 — Blocco 3.pdf", href: "./file/it-orwell-blocco3.pdf", from: "ours" },
  itOrwell4: { name: "Orwell 1984 — Blocco 4.pdf", href: "./file/it-orwell-blocco4.pdf", from: "ours" },
  enModulo: { name: "Modulo compiti estivi.docx", href: "./file/en-modulo.docx", from: "prof" },
  enScheda: { name: "Scheda Dickens.pdf", href: "./file/en-dickens-scheda.pdf", from: "ours" },
  enProg: { name: "Programma svolto Manfredda.pdf", href: "./file/en-programma.pdf", from: "prof" },
  esScheda: { name: "Scheda Sepúlveda.pdf", href: "./file/es-scheda.pdf", from: "ours" },
  fiPdf: { name: "4ALL - fisica.pdf", href: "./file/fi-esercizi.pdf", from: "prof" },
  maPdf: { name: "4ALL - matematica.pdf", href: "./file/ma-esercizi.pdf", from: "prof" },
  maOb: { name: "Obiettivi minimi matematica.pdf", href: "./file/ma-obiettivi.pdf", from: "prof" },
};

const A = {
  school: { kind: "due", date: "2026-09-14", label: "Consegna a inizio scuola" },
  oralIt: { kind: "oral", date: "2026-09-14", label: "A settembre serve saperne parlare (interrogazione / orale)" },
  examEn: { kind: "exam", date: "2026-09-14", label: "Verifica a settembre (Manfredda)" },
  due14: { kind: "due", date: "2026-09-14", label: "Consegna 14 settembre ore 08:00" },
  due12: { kind: "due", date: "2026-09-12", label: "Scadenza 12 settembre" },
  oralZh: { kind: "oral", date: "2026-09-14", label: "Orale al rientro: riassunto e opinioni in cinese" },
  dictZu: { kind: "dictation", date: "2026-09-14", label: "Dettato della Zu al rientro" },
  maybeEs: { kind: "maybe", date: "2026-09-14", label: "Possibile orale/verifica a settembre (in chat non è confermato)" },
};

const CORE = {
  fi: "1,2,3,6,7,8,9,10,11,12,14,15,16,17,19,21,23,26,27,31,32,33,34,36,38,41,43,45,47,48".split(",").map((n) => "fi-" + n),
  ma: ["ma-p1-42", "ma-p1-102a", "ma-p1-103a", "ma-161", "ma-162", "ma-167", "ma-168", "ma-267", "ma-268", "ma-270", "ma-101", "ma-281", "ma-282", "ma-284", "ma-286", "ma-288", "ma-373", "ma-376", "ma-123", "ma-131", "ma-176", "ma-229", "ma-292", "ma-308", "ma-310", "ma-315", "ma-316", "ma-55", "ma-16", "ma-41"],
};

const SHOPS = [
  { id: "pavese", title: "Pavese — La luna e i falò", note: "Pubblico dominio in Italia. Gratis e legale su Liber Liber (anche Wikisource).", href: "https://liberliber.it/autori/autori-p/cesare-pavese/la-luna-e-i-falo/", store: "Liber Liber (gratis, legale)" },
  { id: "orwell", title: "Orwell — 1984", note: "Traduzione italiana: ebook legale (Mondadori/Feltrinelli). Originale inglese: pubblico dominio in UE, da libreria legale o edizione PD.", href: "https://www.lafeltrinelli.it/1984-libro-george-orwell/e/9788804668237", store: "Feltrinelli / Mondadori" },
  { id: "pirandello", title: "Pirandello — Il fu Mattia Pascal", note: "È del 1904: pubblico dominio. Gratis e legale su Liber Liber; oppure ebook Mondadori a pochi euro.", href: "https://www.liberliber.it/online/autori/autori-p/luigi-pirandello/il-fu-mattia-pascal/", store: "Liber Liber (gratis, legale)" },
  { id: "sepulveda", title: "Sepúlveda — Diario de un killer sentimental + Yacaré", note: "In spagnolo, volume Tusquets (ISBN 9788411074100, EPUB). Non prendere la traduzione italiana: il compito è in spagnolo.", href: "https://www.amabook.es/diario-de-un-killer-sentimental-seguido-de-yacare_1", store: "Amabook / Tusquets" },
  { id: "balbi", title: "Balbi — Cercatori di meraviglia", note: "Rizzoli, ebook circa 8 €. Serve per la relazione di fisica (la scrivi tu dopo aver letto).", href: "https://www.lafeltrinelli.it/cercatori-di-meraviglia-ebook-amedeo-balbi/e/9788858667866", store: "Feltrinelli / Kobo" },
];

const DATA = {
  className: "4ALL linguistico",
  school: "Liceo Cairoli — Vigevano",
  subjects: [
    {
      id: "it",
      name: "Italiano",
      teacher: "Classroom — due compiti distinti",
      who: "la prof",
      points: "2 × 100 punti",
      blurb: "Due compiti Classroom, ciascuno da 100 punti.",
      due: "inizio scuola",
      dueDate: "2026-09-14",
      alerts: [A.school, A.oralIt],
      files: [F.itLetture, F.itTracce],
      ask: "LETTURE ESTIVE\nLeggete almeno tre libri tra quelli indicati.\n\nSvolgete un tema di tipologia A, uno di B e uno di C, scegliendo tra le tracce proposte alla scorsa maturità. Niente AI, lavorate con lo scopo di confrontarvi con una vera prova dell’esame di stato. Consegnate i vostri lavori qui in word entro l’inizio della scuola.",
      tasks: [
        {
          id: "it-letture",
          title: "LETTURE ESTIVE — Leggete almeno tre libri tra quelli indicati.",
          files: [F.itLetture],
          alerts: [A.oralIt],
          req: "Testo Classroom: «Leggete almeno tre libri tra quelli indicati.»\n\nAllegato: Letture estive quarta.pptx.pdf. I tre scelti dalla lista ufficiale:",
          children: [
            {
              id: "it-pavese",
              title: "Cesare Pavese — La luna e i falò",
              done: true,
              files: [F.itLetture, F.itPavese1, F.itPavese2, F.itPavese3, F.itPavese4],
              alerts: [A.oralIt],
              req: "Dalla lista della prof. Scelta definitiva (27 agosto 2026). Letto. Schede da stampare (4 blocchi) sotto «Da stampare». Gratis legale: Liber Liber.",
            },
            {
              id: "it-orwell",
              title: "George Orwell — 1984",
              done: true,
              files: [F.itLetture, F.itOrwell1, F.itOrwell2, F.itOrwell3, F.itOrwell4],
              alerts: [A.oralIt],
              req: "Dalla lista della prof. Scelta definitiva (27 agosto 2026). Letto. Schede da stampare (4 blocchi) sotto «Da stampare».",
            },
            {
              id: "it-pirandello",
              title: "Luigi Pirandello — Il fu Mattia Pascal",
              files: [F.itLetture],
              alerts: [A.oralIt],
              req: "Dalla lista della prof. Va letto per intero. Non c’è scheda da consegnare. Gratis legale: Liber Liber / Wikisource.",
            },
          ],
        },
        {
          id: "it-temi",
          title: "Svolgete un tema di tipologia A, uno di B e uno di C, scegliendo tra le tracce proposte alla scorsa maturità. Niente AI, lavorate con lo scopo di confrontarvi con una vera prova dell’esame di stato. Consegnate i vostri lavori qui in word entro l’inizio della scuola.",
          hint: "Niente AI. File Word su Classroom.",
          files: [F.itTracce],
          alerts: [A.school],
          req: "Allegato Classroom: P000_ORD25.pdf (prima prova, sessione ordinaria 2025). Scegli UNA traccia per tipologia.",
          children: [
            {
              id: "it-tema-a",
              title: "Un tema di tipologia A",
              files: [F.itTracce],
              alerts: [A.school],
              req: "Analisi e interpretazione di un testo letterario italiano. Una traccia tra:\n\nA1 — Pier Paolo Pasolini, Appendice I a «Dal diario» (1943-1944).\nA2 — Giuseppe Tomasi di Lampedusa, Il Gattopardo (prima visita di Angelica alla famiglia Salina).",
            },
            {
              id: "it-tema-b",
              title: "Un tema di tipologia B",
              files: [F.itTracce],
              alerts: [A.school],
              req: "Analisi e produzione di un testo argomentativo. Una traccia tra:\n\nB1 — Piers Brendon, Gli anni trenta (New Deal di Roosevelt).\nB2 — Riccardo Maccioni, «Rispetto» parola Treccani 2024 (Avvenire, 17/12/2024).\nB3 — Telmo Pievani, Un quarto d’era (geologica) di celebrità.",
            },
            {
              id: "it-tema-c",
              title: "Un tema di tipologia C",
              files: [F.itTracce],
              alerts: [A.school],
              req: "Riflessione critica espositivo-argomentativa su tematiche di attualità. Una traccia tra:\n\nC1 — Paolo Borsellino, I giovani, la mia speranza (Epoca, 14/10/1992).\nC2 — Anna Meldolesi e Chiara Lalli (7-Sette / Corriere della Sera, 13/12/2024).",
            },
          ],
        },
      ],
    },
    {
      id: "en",
      name: "Inglese",
      teacher: "Simone Manfredda + lettorato",
      who: "il prof",
      points: "lettorato 100 punti",
      blurb: "Due compiti Classroom: Manfredda + lettorato.",
      due: "inizio scuola",
      dueDate: "2026-09-14",
      alerts: [A.examEn, A.school],
      files: [F.enModulo, F.enScheda, F.enProg],
      ask: "SUMMER HOMEWORK & PROGRAMMA SVOLTO\n«Durante il periodo estivo gli studenti dovranno svolgere con cura le attività indicate di seguito, con l’obiettivo di consolidare le competenze linguistiche acquisite nel corso dell’anno.\nLettura obbligatoria: A Christmas Carol by Charles Dickens (PDF su Google Classroom).\nGli esercizi sono facoltativi. Ciò che resta obbligatoria è la lettura del libro, che sarà oggetto di valutazione a settembre e sarà parte del programma di quinta. Fissa quindi bene la trama, i personaggi e le tematiche che emergono dalla lettura prendendo appunti sul quaderno.»\n\nSUMMER HOMEWORK (LETTORATO) — 100 punti: Performer B2 Unit 6 «Save the Earth» + due video con domande.",
      tasks: [
        {
          id: "en-dickens-read",
          title: "Lettura obbligatoria: A Christmas Carol by Charles Dickens (PDF su Google Classroom).",
          who: "Manfredda",
          files: [F.enModulo],
          alerts: [A.examEn],
          req: "Dal modulo del 03/06/2026. «Ciò che resta obbligatoria è la lettura del libro, che sarà oggetto di valutazione a settembre e sarà parte del programma di quinta.» Il PDF sta su Classroom.",
        },
        {
          id: "en-dickens-notes",
          title: "Fissa quindi bene la trama, i personaggi e le tematiche che emergono dalla lettura prendendo appunti sul quaderno.",
          hint: "Scheda già fatta: copiala sul quaderno.",
          done: true,
          who: "Manfredda",
          files: [F.enScheda, F.enModulo],
          alerts: [A.examEn],
          req: "Testo letterale del modulo. Gli appunti vanno sul quaderno.",
        },
        {
          id: "en-reader",
          title: "Gli esercizi sono facoltativi.",
          optional: true,
          who: "Manfredda",
          files: [F.enModulo],
          req: "Testo del modulo. Se li fai, sono gli esercizi del reader di A Christmas Carol su Classroom.",
        },
        {
          id: "en-106",
          title: "Performer B2 Unit 6 «Save the Earth» — pagina 106, esercizi 1, 2, 3, 4 e 5.",
          who: "il lettorato",
          alerts: [A.school],
          req: "SUMMER HOMEWORK (LETTORATO), 100 punti. Unit 6 «Save the Earth», coursebook Performer B2.\nPagina 106: esercizi 1, 2, 3, 4 e 5. Da consegnare su Classroom (insieme al resto del lettorato) per l’inizio della scuola.",
        },
        {
          id: "en-108",
          title: "Performer B2 Unit 6 — pagina 108, esercizio 1.",
          who: "il lettorato",
          alerts: [A.school],
          req: "Stesso compito lettorato (100 punti). Pagina 108: solo l’esercizio 1.",
        },
        {
          id: "en-110",
          title: "Performer B2 Unit 6 — pagina 110, esercizi 1, 2, 3 e 4.",
          who: "il lettorato",
          alerts: [A.school],
          req: "Stesso compito lettorato (100 punti). Pagina 110: esercizi 1, 2, 3 e 4.",
        },
        {
          id: "en-114",
          title: "Active Citizenship LAB — pagina 114, esercizi 3 e 4.",
          who: "il lettorato",
          alerts: [A.school],
          req: "Active Citizenship LAB, stesso compito lettorato (100 punti). Pagina 114: esercizi 3 e 4.",
        },
        {
          id: "en-v1",
          title: "Video: Why I live a zero waste life — rispondi alle domande.",
          who: "il lettorato",
          href: "https://www.youtube.com/watch?v=pF72px2R3Hg",
          alerts: [A.school],
          req: "Lettorato, 100 punti. Guarda il video (Lauren Singer, TEDxTeen) e rispondi in inglese:\n\n1. According to the video, how can you achieve a zero-waste lifestyle?\n2. Do you think you would be able to go zero waste? Why? Why not?",
        },
        {
          id: "en-v2",
          title: "Video: The Simple Solution to Fast Fashion — rispondi alle domande.",
          who: "il lettorato",
          href: "https://www.youtube.com/watch?v=Bh8dnw67rE0",
          alerts: [A.school],
          req: "Lettorato, 100 punti. Guarda il video (Josephine Philips, TED — «The climate solution in your closet») e rispondi in inglese:\n\n1. How often do you buy new clothes?\n2. What questions do you ask yourself before buying new stuff (if any)?\n3. Do you have a clothing item you are particularly affectionate about? What about any other possession?",
        },
        {
          id: "en-consegna",
          title: "SUMMER HOMEWORK (LETTORATO) — consegnare su Classroom.",
          who: "il lettorato",
          alerts: [A.school],
          req: "Compito Classroom «SUMMER HOMEWORK (LETTORATO)», 100 punti. Data di consegna non impostata: comunque per l’inizio della scuola.\n\nDa consegnare: esercizi Unit 6 (pp. 106, 108, 110, 114) + risposte ai due video. Dickens non si consegna: si legge e si studia per la verifica di Manfredda.",
        },
      ],
    },
    {
      id: "es",
      name: "Spagnolo",
      teacher: "Dalla chat di classe (Elisa, Aurora) — non c’è il post Classroom",
      who: "la prof (finora solo dalla chat)",
      blurb: "Sepúlveda: due storie nello stesso volume. In chat risulta solo la lettura.",
      due: "inizio scuola",
      dueDate: "2026-09-14",
      alerts: [A.maybeEs],
      files: [F.esScheda],
      ask: "Fonte: chat di classe, non un compito Classroom ufficiale. Elisa ha mandato la copertina; Aurora il PDF (103 pp., Tusquets).\n\nLibro: Luis Sepúlveda, Diario de un killer sentimental seguido de Yacaré (due novelas cortas nello stesso volume).\n\nDalla chat NON risultano: data di consegna, verifica, relazione, appunti obbligatori, extra per debito. Finché non arriva il post della prof, il compito è leggere entrambe le storie in spagnolo.\n\nGli appunti (trama, personaggi, temi) non sono richiesti per iscritto: servono se a settembre c’è orale o verifica.",
      tasks: [
        {
          id: "es-libro",
          title: "Luis Sepúlveda — Diario de un killer sentimental seguido de Yacaré",
          files: [F.esScheda],
          alerts: [A.maybeEs],
          req: "Dalla chat di classe (non c’è ancora il post Classroom della prof): leggere il volume, in spagnolo. Due novelas cortas nello stesso libro.",
          children: [
            {
              id: "es-diario",
              title: "Diario de un killer sentimental",
              files: [F.esScheda],
              alerts: [A.maybeEs],
              req: "Prima storia del volume. Va letta in spagnolo.",
            },
            {
              id: "es-yacare",
              title: "Yacaré",
              files: [F.esScheda],
              alerts: [A.maybeEs],
              req: "Seconda storia dello stesso volume. Va letta anche questa.",
            },
          ],
        },
      ],
    },
    {
      id: "ar",
      name: "Storia dell’arte",
      short: "Arte",
      teacher: "Cristina Bertucci",
      who: "Bertucci",
      blurb: "Niente consegna su Classroom. Programma su Spaggiari + libro a piacere.",
      due: "inizio scuola",
      ask: "Messaggio Classroom (non è un compito da consegnare). Due indicazioni:\n\n1) Recuperare il programma svolto su Spaggiari, nella sezione apposita.\n2) Lettura consigliata a piacere: un libro, scelto tra i tre indicati, collegato al programma dell’anno, per arricchire il bagaglio culturale. Chiude con «buone vacanze».\n\nNiente tema, scheda o orale indicati. Hai scelto Lomartire, La dama e il Moro.",
      tasks: [
        {
          id: "ar-spaggiari",
          title: "Recuperare il programma svolto su Spaggiari, nella sezione apposita.",
          req: "La prof ha caricato il programma svolto sulla piattaforma Spaggiari, sezione apposita. Entra, aprilo, rileggi gli argomenti dell’anno. Serve anche per scegliere il libro in modo coerente con quanto fatto in classe. Non si consegna nulla.",
        },
        {
          id: "ar-libro",
          title: "Lettura consigliata a piacere: un libro scelto tra quelli indicati, in relazione al programma svolto, per arricchire il bagaglio culturale.",
          optional: true,
          hint: "Lettura consigliata, non obbligatoria.",
          req: "Testo Classroom: durante l’estate leggere un libro a piacere tra quelli indicati, in relazione al programma svolto, per arricchire il bagaglio. Sceglierne 1 tra:\n\n1. Carla Maria Russo — La figlia più amata (sorelle Medici)\n2. Maria Bellonci — Rinascimento privato (Isabella d’Este)\n3. Carlo Maria Lomartire — La dama e il Moro (Cecilia Gallerani, La dama con l’ermellino di Leonardo, Ludovico il Moro, Milano sforzesca)\n\nLa tua scelta: il n. 3. Non è indicata una consegna. Facoltativo nel senso di «consigliato», non compito da ritirare.",
        },
      ],
    },
    {
      id: "fi",
      name: "Fisica",
      teacher: "Roberto Maccagnola",
      who: "Maccagnola",
      points: "100 punti",
      blurb: "Teoria + esercizi in nero + Balbi con relazione. Consegna 14 settembre ore 08:00.",
      due: "14 set 08:00",
      dueDate: "2026-09-14",
      alerts: [A.due14],
      files: [F.fiPdf],
      ask: "Classroom: «lavoro estivo di fisica» — 100 punti. Consegna 14 settembre ore 08:00. «Seguire le indicazioni presenti nel file allegato» (4ALL - fisica.pdf).\n\nPost del 17 giugno: «ho inserito i compiti delle vacanze differenziandoli tra compiti e esercizi aggiuntivi per chi ha il debito. Gli esercizi aggiuntivi per chi ha il debito sono assegnati anche agli studenti che hanno raggiunto la sufficienza con aiuto.»\n\nTre parti:\n1) Ripasso di teoria di tutto il programma realmente svolto in quarta (appunti o libro).\n2) Esercizi dal PDF: senza debito fai SOLO quelli digitati in nero. Debito o sufficienza con aiuto: neri + evidenziati. I colori si vedono solo nel PDF originale.\n3) Leggere Cercatori di meraviglia (Amedeo Balbi) e fare una piccola relazione.\n\nTu non hai debito: solo neri + libro + relazione. Tocca «Cosa chiede il prof» sotto ogni esercizio per il testo completo (così non ti serve il PDF in tasca).",
      tasks: [
        {
          id: "fi-teoria",
          title: "Ripassare la teoria di tutti gli argomenti presenti nel programma realmente svolto di quarta (appunti oppure libro).",
          files: [F.fiPdf],
          alerts: [A.due14],
          req: "Richiesta nel PDF: ripassare la teoria di tutti gli argomenti presenti nel programma realmente svolto di quarta (appunti oppure libro).\n\nArgomenti che ricorrono negli esercizi: pressione e fluidi (Pascal, Torricelli, spinta idrostatica); momento angolare e d’inerzia; moto circolare, caduta, pendolo, energia, lavoro; gravità, orbite, fuga, buchi neri; molle e montagne russe; suono (Doppler, intensità, dB); ottica (riflessione, rifrazione, specchi, onde EM).",
        },
        {
          id: "fi-colori",
          title: "Nel file allegato: svolgere solo gli esercizi digitati in nero (non quelli evidenziati, se non hai debito).",
          files: [F.fiPdf],
          alerts: [A.due14],
          req: "Il prof differenzia neri / evidenziati. Questo elenco ha tutti e 48 i testi, ma i colori NON si vedono qui. Prima di spuntare «svolti i neri», apri 4ALL - fisica.pdf e segna quali sono in nero. Gli esercizi 13 e 32 hanno una figura: usala dal PDF.",
        },
        {
          id: "fi-neri",
          title: "Svolgere gli esercizi digitati in nero.",
          hint: "Spunta sotto solo quelli neri del PDF. Gli evidenziati non ti spettano.",
          files: [F.fiPdf],
          alerts: [A.due14],
          req: "Regola: senza debito solo i problemi digitati in nero. Svolgi il procedimento (non basta il risultato). 13 e 32: c’è la figura nel PDF.",
          children: items("fi", [
            [1, "Cubo sotto vuoto — forza sul coperchio", "Un cubo di 1 m di spigolo è sottoposto alla pressione standard e viene chiuso con un coperchio quadrato delle stesse dimensioni dello spigolo. Una volta chiuso dal cubo viene aspirata tutta l’aria. Calcola la forza necessaria per aprire il cubo."],
            [2, "Ciaspole sulla neve — pressione", "Un escursionista di 90 kg usa un paio di ciaspole da 0,022 m². Qual è la pressione che l’escursionista esercita sulla neve?"],
            [3, "Torchio idraulico — auto 1600 kg", "Un torchio idraulico presenta due superfici di 0,002 m² e 1,45 m²; se devo sollevare un’autovettura da 1600 kg, quale forza devo applicare al pedale?"],
            [4, "Barometro su altro pianeta", "Un astronauta arriva su un pianeta con accelerazione di gravità di 8,61 m/s². Osserva un barometro di Torricelli: la colonnina di mercurio è alta 1,23 m. A quale pressione è sottoposto l’astronauta? Esprimi il risultato in Pa e in atm. (densità del mercurio 13600 kg/m³, 1 atm = 101300 Pa)"],
            [5, "Idroboot 5 km — forza sulla lente", "Un idroboot dispone di una telecamera con una lente da 76 cm²; se scende alla profondità di 5 km, a quale forza deve resistere la lente? (densità acqua di mare 1033 kg/m³)"],
            [6, "Sommergibile 1200 kPa — profondità", "Un sommergibile può sopportare una pressione di 1200 kPa; quale profondità può raggiungere? (densità dell’acqua di mare 1033 kg/m³)"],
            [7, "Satellite cilindrico — L e I", "Un satellite ha forma cilindrica con raggio 1,2 m e altezza 4 m. Massa 3 tonnellate; ruota attorno all’asse del cilindro con periodo 1,2 s. Dopo aver dispiegato i pannelli solari il periodo si allunga a 8,3 s. Determina: a) la variazione di momento angolare; b) la variazione del momento d’inerzia."],
            [8, "ISS — astronauta e casse", "Nella ISS un astronauta di massa 75 kg sposta casse di rifiuti di 150 kg. Ad ogni cassa imprime una velocità di 0,8 m/s. Durante lo spostamento della 4ª cassa si rompe l’ancoraggio e l’astronauta balza all’indietro. Determina il modulo della velocità acquisita dall’astronauta."],
            [9, "Satellite — nuovo momento d’inerzia", "Un satellite con momento d’inerzia di 12000 kg m² ruota inizialmente a 2 rad/s. Dopo aver dispiegato quattro antenne riduce la velocità angolare a 0,7 rad/s. Calcola il nuovo momento d’inerzia."],
            [10, "Ciclista pista circolare — periodo", "Un ciclista percorre una pista circolare di raggio 29 m alla velocità di 15 m/s. Determina il periodo del moto."],
            [11, "Sfera da 3,8 m — velocità al suolo", "Una sfera viene lasciata cadere dall’altezza di 3,8 m; con quale velocità raggiungerà il suolo?"],
            [12, "Pendolo 8 kg — periodo e energia", "Un pendolo è composto da una massa di 8 kg appesa con un cavo d’acciaio di 25 m. Compie oscillazioni di ampiezza 3°. Determina il periodo di oscillazione e l’energia meccanica."],
            [13, "Scivolo con cunetta (figura)", "Una sfera di massa 8 kg scende lungo uno scivolo di altezza totale 25 m; lo scivolo presenta una cunetta alta 9 m. Determina la velocità della sfera alla fine dello scivolo e sulla cima della cunetta.\nC’è la figura nel PDF: usala."],
            [14, "Skypass Alpe di Siusi — lavoro", "Uno skypass porta uno sciatore da una stazione a 860 m slm all’inizio di una pista sull’Alpe di Siusi a 1835 m slm. Sciatore 92 kg: determina il lavoro compiuto dallo skypass."],
            [15, "Treno e molle in stazione", "Un treno di massa 18500 kg entra in stazione a 15 km/h e urta un sistema di molle che deve assorbire la sua energia in 30 cm. Determina la costante elastica k e la forza massima generata dalle molle."],
            [16, "Pistola giocattolo — molla", "Una pistola giocattolo spara pallini di plastica da 2 g con una molla k = 10 N/m. Quando è carica la molla è accorciata di 4 cm; determina la velocità con cui i pallini escono dalla molla."],
            [17, "Trampolino da sci — gittata", "In una gara con trampolino uno sciatore percorre una pista con dislivello di 780 m e raggiunge un trampolino orizzontale. Calcola la velocità al termine del trampolino e la gittata del salto."],
            [18, "Auto al passo alpino — lavoro", "Un’auto di massa 1300 kg parte da un paese a 365 m slm e raggiunge un passo alpino a 2086 m slm. Determina il lavoro svolto dall’auto."],
            [19, "g su un pianeta", "Determina l’accelerazione di gravità su un pianeta di massa 5,6 × 10²⁷ kg e raggio 22300 km."],
            [20, "Sistema binario — distanza", "Un sistema binario: due stelle, 2,3 e 4,6 masse solari. Qual è la distanza tra le stelle se il periodo è 32,8 giorni? (1 massa solare = 2 × 10³⁰ kg)"],
            [21, "Titano — orbita e fuga", "Il satellite Titano di Saturno (massa di Saturno 5,68 × 10²⁶ kg) ha periodo 15,94 giorni. Determina la distanza media orbitale di Titano, la velocità orbitale, e la sua velocità di fuga (massa 1,34 × 10²³ kg, raggio 2575 km)."],
            [22, "Navicella Encelado → Rea", "Calcola il lavoro necessario per traghettare una navicella di 3400 kg dall’orbita di Encelado (238000 km dal centro di Saturno) all’orbita di Rea (527000 km)."],
            [23, "Forza Terra–Venere", "Durante il transito di Venere davanti al Sole la minima distanza dalla Terra è 32 milioni di km. Massa Terra 6 × 10²⁴ kg, Venere 4,8 × 10²⁴ kg: intensità della forza di attrazione tra i due pianeti?"],
            [24, "Ganimede — periodo e fuga", "Ganimede orbita Giove (massa 1,9 × 10²⁷ kg) a 1,07 milioni di km. Determina periodo orbitale, velocità orbitale e velocità di fuga (massa 1,48 × 10²³ kg, raggio 2631 km)."],
            [25, "Titano 5580 m/s — massa di Saturno", "Titano orbita a 5580 m/s a 1,22 × 10⁹ m da Saturno. Determina la massa di Saturno."],
            [26, "Auto e autovelox — forza frenante", "Un’auto di 1200 kg, dopo l’avviso di un autovelox, riduce la velocità da 90 km/h a 50 km/h in 800 m. Qual è l’intensità della forza frenante? Qual è il lavoro della forza frenante?"],
            [27, "Corpo celeste — g, fuga, orbita", "Corpo celeste: raggio 2995 km, massa 2 × 10²³ kg. Determina: a) g in superficie; b) velocità di fuga; c) velocità orbitale di un satellite di 100 kg a 12000 km di distanza; d) energia meccanica totale di tale corpo in orbita."],
            [28, "Sole e Adara — attrazione", "Sole 2 × 10³⁰ kg, dista da Adara 3,78 × 10¹⁸ m. Massa di Adara 2,4 × 10³¹ kg: forza di attrazione tra le due stelle."],
            [29, "Raggio buco nero", "Calcola il raggio di un buco nero di massa 2 × 10³⁷ kg."],
            [30, "Vostok Strelka e Bielka", "Agosto 1960: capsula Vostok con Strelka e Bielka, orbita ellittica, apogeo 324 km, perigeo 287 km. Calcola la velocità al perigeo e all’apogeo."],
            [31, "Palla e molla verticale", "Una palla di 0,28 kg è lanciata da una molla verticale k = 1,2 N/m, compressa di 78 cm. Determina l’altezza raggiunta dalla palla."],
            [32, "Montagne russe (figura)", "Un carrello scivola sulle montagne russe (figura nel PDF). Massa 40 kg, velocità iniziale 5 m/s. Determina: a) velocità in B, C, D (h₁ = 46 m, h₂ = 32 m, h₃ = 29 m); b) energia meccanica del carrello; c) energia cinetica massima e velocità massima.\nUsa la figura del PDF."],
            [33, "Doppler ambulanza", "Un passante si muove nello stesso verso dell’ambulanza a 6 m/s. Inizialmente l’ambulanza si avvicina a 86 km/h con sirena a 1430 Hz. Calcola la frequenza iniziale ricevuta dal passante e quella percepita dopo il transito."],
            [34, "Impulso sonoro — due uditori", "Un impulso sonoro di potenza 10⁻³ W è emesso da un punto O. Primo uditore a 10 m, secondo a una distanza 20 volte maggiore. Calcola le intensità in decibel ricevute dai due uditori."],
            [35, "Martello pneumatico — distanze", "Rossi sente un martello pneumatico a 126 m: riceve 2 × 10⁻⁴ W/m²; l’amico riceve 5 × 10⁻⁸ W/m². A quale distanza è l’amico e quali sono le intensità in decibel?"],
            [36, "Botto 1600 W a 600 m", "Un botto da 1600 W è percepito fino a 600 m. Calcola l’intensità sonora in W/m² e in decibel a quella distanza."],
            [37, "Fischietto per cani 32 kHz", "Un fischietto emette a 32000 Hz. Frequenza percepita da un cane che ti corre incontro a 30 m/s? E se si allontana alla stessa velocità, o se il cane è fermo ma ti stai avvicinando tu? (v suono = 340 m/s)"],
            [38, "Rifrazione n=1,46 → 1,21", "Un raggio incide a 30° rispetto alla normale da un mezzo n = 1,46 a un mezzo n = 1,21. Calcola: a) velocità della luce nei due mezzi; b) angolo del raggio riflesso e del raggio rifratto; c) angolo limite per la riflessione totale."],
            [39, "Due aerei — Doppler", "Due aerei sulla stessa direzione ma verso opposto: 200 m/s e 150 m/s. Calcola la frequenza percepita da ciascun aereo se sono in avvicinamento e ciascuno emette 1000 Hz."],
            [40, "Sorgente 40 W a 1 km", "Sorgente sonora 40 W percepita a 1 km. Calcola l’intensità a quella distanza e la distanza alla quale si ottiene un’intensità di 10 dB."],
            [41, "Sirena carabinieri 5000 Hz", "Una vettura dei carabinieri emette 5000 Hz e si avvicina a un passante a 80 km/h. Calcola la frequenza percepita."],
            [42, "Sorgente 50 W a 500 m", "Un uditore sente una sorgente a 500 m che emette 50 W. Calcola l’intensità nel SI e in decibel."],
            [43, "52 dB a 10 m — potenza", "Un’onda sonora a 10 m dalla sorgente è percepita a 52 dB. Calcola la potenza emessa."],
            [44, "Onda sismica — velocità", "Un’onda sismica ha lunghezza d’onda 18 m e frequenza 1,2 Hz. Calcola la velocità di propagazione."],
            [45, "Specchio concavo e candela", "A 15 m da uno specchio concavo con raggio di curvatura 10 m c’è una candela alta 15 cm. A quale distanza e che tipo di immagine si forma?"],
            [46, "800 W a 30 km", "Sorgente sonora 800 W: intensità percepita a 30 km? Nel SI e in decibel."],
            [47, "Onda EM 2,16×10¹⁵ Hz", "Un’onda elettromagnetica ha frequenza 2,16 × 10¹⁵ Hz; determina energia, lunghezza d’onda, e lunghezza d’onda in un mezzo con n = 1,56."],
            [48, "Onda 740 nm in un materiale", "Un’onda EM ha lunghezza d’onda 740 nm dentro un materiale trasparente con n = 1,34. Calcola la lunghezza d’onda nel vuoto e la sua energia, e spiega se la radiazione è visibile per un essere umano."],
          ]),
        },
        {
          id: "fi-evidenziati",
          title: "Esercizi evidenziati (debito / sufficienza con aiuto)",
          optional: true,
          files: [F.fiPdf],
          alerts: [A.due14],
          req: "Post Classroom del 17 giugno: gli extra evidenziati sono per chi ha il debito formativo o ha preso la sufficienza con aiuto. Tu non hai debito: non ti spettano. Restano nascosti finché non premi Facoltativi.",
        },
        {
          id: "fi-balbi",
          title: "Leggere Cercatori di meraviglia (Amedeo Balbi).",
          alerts: [A.due14],
          req: "Post Classroom del 5 giugno: «il libro che vorrei proporre».\n\nAmedeo Balbi, Cercatori di meraviglia. Storie di grandi scienziati curiosi del mondo (Rizzoli, 2021, 252 pp.). Storia della scienza attraverso la curiosità (Galileo, Faraday, Becquerel, Cavendish…). Va letto. La relazione è il punto successivo.",
        },
        {
          id: "fi-relazione",
          title: "Fare una piccola relazione del libro.",
          hint: "La scrivi tu. Consegna insieme al lavoro estivo.",
          files: [F.fiPdf],
          alerts: [A.due14],
          req: "Nel PDF: «Leggere e fare una piccola relazione del libro». Il prof non precisa lunghezza né formato: relazione breve, chiara, tua. Consegnarla insieme al lavoro estivo entro il 14 settembre ore 08:00. Non farla scrivere all’AI: è parte del compito da 100 punti.",
        },
        {
          id: "fi-consegna",
          title: "lavoro estivo di fisica — consegna 14 settembre ore 08:00.",
          files: [F.fiPdf],
          alerts: [A.due14],
          req: "Compito Classroom «lavoro estivo di fisica», 100 punti. Scadenza: 14 settembre 2026, ore 08:00. Insieme: esercizi (neri) + piccola relazione sul Balbi.",
        },
      ],
    },
    {
      id: "ma",
      name: "Matematica",
      teacher: "Roberto Maccagnola",
      who: "Maccagnola",
      points: "100 punti",
      blurb: "Teoria + colonna sinistra / «per tutti». Consegna 14 settembre ore 08:00.",
      due: "14 set 08:00",
      dueDate: "2026-09-14",
      alerts: [A.due14],
      files: [F.maPdf, F.maOb],
      ask: "Classroom: «esercizi per le vacanze» — 100 punti. Consegna 14 settembre ore 08:00. «Segui le istruzioni presenti nel file allegato» (4ALL - matematica.pdf).\n\nStesso post del 17 giugno di fisica: extra per debito e per chi ha preso la sufficienza con aiuto.\n\nCosa fare (niente debito):\n1) Ripassare tutta la teoria dell’anno (goniometria, trigonometria, esponenziali e logaritmi — obiettivi minimi 4A linguistico).\n2) Svolgere gli esercizi della colonna di sinistra e le sezioni «per tutti». La colonna di destra e i blocchi «solo debito» NON ti spettano.\n\nA destra di molti esercizi ci sono già i risultati in blu: autocontrollo; va comunque svolto il procedimento.\n\nNon fare: pag. 2–4 colonna destra; pag. 5 es. 329–336; pag. 6 eq. 337–344.\nLe figure (pag. 1 e pag. 6) stanno nel PDF. Tocca «Cosa chiede il prof» sotto ogni esercizio per testo e risultato blu.",
      tasks: [
        {
          id: "ma-teoria",
          title: "Ripassare tutta la teoria dell’anno (goniometria, trigonometria, esponenziali e logaritmi).",
          files: [F.maOb],
          alerts: [A.due14],
          req: "Ripassare tutta la teoria dell’anno. Dal file obiettivi minimi 4A linguistico (allegato Classroom):\n\nGoniometria: grafici delle funzioni elementari, relazioni fondamentali, archi associati, equazioni goniometriche elementari.\nTrigonometria: teoremi in problemi semplici.\nEsponenziali e logaritmi: grafici elementari, proprietà dei logaritmi, equazioni e disequazioni semplici.",
        },
        {
          id: "ma-p1",
          title: "Dal file allegato, pagina 1: LEGGI IL GRAFICO (42–44); problemi 102 e 103.",
          files: [F.maPdf],
          alerts: [A.due14],
          req: "Sezione esponenziali. 42–44: «LEGGI IL GRAFICO» — nelle figure sono disegnati grafici di funzioni esponenziali; scrivi le equazioni corrispondenti (figure nel PDF). Poi i problemi 102 (Piegare all’infinito) e 103 (Larve e anatre).",
          children: items("ma-p1", [
            [42, "Grafico esponenziale decrescente", "LEGGI IL GRAFICO (figura nel PDF). Grafico decrescente; passa per A(2, 1/9) e in genere per (0, 1). Scrivi l’equazione della funzione esponenziale."],
            [43, "Grafico esponenziale crescente", "LEGGI IL GRAFICO. Grafico crescente; interseca l’asse y in (0, 1/8); A(−3/2, 1). Scrivi l’equazione."],
            [44, "Grafico esponenziale decrescente", "LEGGI IL GRAFICO. Grafico decrescente; passa per (0, 1) e A(−1/2, √2). Scrivi l’equazione."],
            ["102a", "Piegare all’infinito — area", "Foglio di area 10 dm² e spessore 0,1 mm, piegato a metà ripetutamente: ad ogni piega l’area si dimezza e lo spessore raddoppia.\nTEST — Quale funzione rappresenta l’area A (in dm²) in funzione del numero di pieghe x?\nA) A(x) = 10 · (1/2)^x\nB) A(x) = 10 · x/2\nC) A(x) = 10 · x²\nD) A(x) = 10 · 2^x"],
            ["102b", "Piegare all’infinito — spessore", "Stesso foglio. TEST — Quale funzione rappresenta lo spessore s (in mm) in funzione di x?\nA) s(x) = 0,1 · 2 · x\nB) s(x) = 0,1 · 2 · x²\nC) s(x) = 0,1 · 2^x\nD) s(x) = 0,1 · (1/2)^x"],
            ["102c", "Piegare 20 volte vs Big Ben", "Con la calcolatrice: se si piegasse 20 volte, lo spessore supererebbe l’altezza del Big Ben (96 m) di quasi 9 m. Verificalo."],
            ["103a", "Larve infette — tabella e grafico", "Tossina tra gli uccelli in Toscana (2015). y(t) = y₀ e^{kt}, y(t) = larve infette, t in giorni.\nA t = 0 ci sono 50 larve infette. Tabella per i primi 5 giorni con k = 1,1 e grafico."],
            ["103b", "Larve — confronto k=0,5", "Come cambia il grafico se k diventa 0,5? Confronta i due grafici."],
          ]),
        },
        {
          id: "ma-p2",
          title: "Dal file allegato, pagina 2: colonna di sinistra e sezione «per tutti».",
          files: [F.maPdf],
          alerts: [A.due14],
          req: "Colonna sinistra: risolvi le equazioni esponenziali 160–170 e le disequazioni 267–272. Poi, sezione «per tutti»: semplifica i logaritmi 101–106. I risultati blu nel PDF sono solo autocontrollo.",
          children: items("ma", [
            [160, "4^x = 2^x − 2", "Risolvi (colonna sinistra). Autocontrollo PDF: impossibile."],
            [161, "8 + 2^{x+1} = 2^{2x}", "Risolvi. Autocontrollo PDF: 2."],
            [162, "9^x − 3 = 2 · 3^x", "Risolvi. Autocontrollo PDF: 1."],
            [163, "3^{2x} − 9·3^x + 3 = (1/3)·3^x", "Risolvi. Autocontrollo PDF: −1 ; 2."],
            [164, "5^{2x} − 5^x = 5^{x−2} − 1/25", "Risolvi. Autocontrollo PDF: 0 ; −2."],
            [165, "2/(3^x − 1) = 1/(3^x − 5)", "Risolvi. Autocontrollo PDF: 2."],
            [166, "2^x + 8 = 1/4 + 2^{1−x}", "Risolvi. Autocontrollo PDF: −2."],
            [167, "10^x + 10^{2−x} = 101", "Risolvi. Autocontrollo PDF: 0 ; 2."],
            [168, "9^x + 9 = 10 · 3^x", "Risolvi. Autocontrollo PDF: 0 ; 2."],
            [169, "2^{x+3} + 4^{x+1} = 320", "Risolvi. Autocontrollo PDF: 3."],
            [170, "2^{x+1} + 2^{3−x} = 17", "Risolvi. Autocontrollo PDF: −1 ; 3."],
            [267, "(1/3)^{x²+x} < 1/9", "Disequazione esponenziale, colonna sinistra. Autocontrollo PDF: x < −2 ∨ x > 1."],
            [268, "e^x · e^{x−3} ≥ √e", "Disequazione. Autocontrollo PDF: x ≥ 7/4."],
            [269, "e^{x²−6} · e^x < 1", "Disequazione. Autocontrollo PDF: −3 < x < 2."],
            [270, "(2^x − 4)/(1 − 3^x) > 0", "Disequazione. Autocontrollo PDF: 0 < x < 2."],
            [271, "(4 − 8^x)/(3^x + 9) ≤ 0", "Disequazione. Autocontrollo PDF: x ≥ 2/3."],
            [272, "45 · 2^{2x−2} < −35 · 4^{x−1}", "Disequazione. Autocontrollo PDF: impossibile."],
            [101, "2 log(x²−1) − log(x+1) − log(x−1)", "Semplifica (logaritmi, per tutti). Autocontrollo PDF: log[(x+1)(x−1)]."],
            [102, "(1/2) log₃ x + 2 log₃(x+1) − log₃ 7", "Semplifica. Autocontrollo PDF: log₃ [√x (x+1)² / 7]."],
            [103, "(1/2)(log 7 + log x − log 3) + log √(3x)", "Semplifica. Autocontrollo PDF: log(x√7)."],
            [104, "log(x−1)+log(x−2)−log(x+3)", "Semplifica. Autocontrollo PDF: log[(x−1)(x−2)/(x+3)]."],
            [105, "(1/2)[log₂ a + 2 log₂(a+4)] − log₂(a−1)", "Semplifica. Autocontrollo PDF: log₂ [√a · (a+4) / (a−1)]."],
            [106, "log₂(x+1)+5 log₂(x−1)−4 log₂(x²−1)", "Semplifica. Autocontrollo PDF: log₂ [(x−1)/(x+1)³]."],
          ]),
        },
        {
          id: "ma-p3",
          title: "Dal file allegato, pagina 3: colonna di sinistra e sezione «per tutti».",
          files: [F.maPdf],
          alerts: [A.due14],
          req: "Colonna sinistra: equazioni e disequazioni logaritmiche 281–290 e 373–376. Poi, per tutti: calcola i valori goniometrici 123–125; dati seno/coseno e quadrante, trova l’altra funzione (131–134).",
          children: items("ma", [
            [281, "log₂ x = −5", "Risolvi. Autocontrollo PDF: 1/32."],
            [282, "log₄(x+2) = 2", "Risolvi. Autocontrollo PDF: 14."],
            [283, "log₅(x² − 4) = 1", "Risolvi. Autocontrollo PDF: ±3."],
            [284, "log₂(2x−1) = log₂(x+3)", "Risolvi. Autocontrollo PDF: 4."],
            [285, "log₃(x+1) + 2 log₃ 2 = log₃(x+7)", "Risolvi. Autocontrollo PDF: 1."],
            [286, "log(x−2) + log 5 = log x", "Risolvi. Autocontrollo PDF: 5/2."],
            [287, "5 log² x − log x = 0", "Risolvi. Autocontrollo PDF: 1 ; ¹⁰√5 (nel PDF compare anche 1 ; ⁵√10 — verifica)."],
            [288, "ln² x − 9 = 0", "Risolvi. Autocontrollo PDF: e^{−3} ; e³."],
            [289, "log_x 3 = 1/3", "Risolvi. Autocontrollo PDF: 27."],
            [290, "ln((x−4)/(2x+1)) = 0", "Risolvi. Autocontrollo PDF: −5."],
            [373, "log₄(x−1) ≤ −2", "Disequazione. Autocontrollo PDF: 1 < x ≤ 17/16."],
            [374, "log_{1/3}(1−2x) < 1", "Disequazione. Autocontrollo PDF: x < 1/3 (verifica il dominio nel PDF)."],
            [375, "log_{1/2}(x+3) < −1", "Disequazione. Autocontrollo PDF: x > −1 (verifica il dominio nel PDF)."],
            [376, "log(x²+17x+16) < 2", "Disequazione. Autocontrollo PDF: −21 < x < −16 ∨ −1 < x < 4."],
            [123, "Valore goniometrico", "Calcola (per tutti): cos 4π + 2 sin(−15π/2) + (1/3) cos(−3π) + sin(9π/2).\nAutocontrollo PDF: 11/3."],
            [124, "Valore goniometrico", "Calcola: [sin(7π/2) − cos(−7π) + 2 sin(−11π/2)] / [2 sin(−3π/2) + cos 4π − 4 cos(5π/2)].\nAutocontrollo PDF: 2/3."],
            [125, "Valore goniometrico", "Calcola: [4(cos² 2π + sin²(5π/2)) + 8 cos 10π] / [3(1 − 4 cos(−4π))].\nAutocontrollo PDF: −16/9."],
            [131, "sin α=7/25 → cos α", "Dato sin α = 7/25, 0 < α < π/2, trova cos α. Autocontrollo PDF: 24/25."],
            [132, "cos α=−4/5 → sin α", "Dato cos α = −4/5, π < α < 3π/2, trova sin α. Autocontrollo PDF: −3/5."],
            [133, "sin α=1/3 → cos α", "Dato sin α = 1/3, π/2 < α < π, trova cos α. Autocontrollo PDF: −2√2 / 3."],
            [134, "sin α=−2/5 → cos α", "Dato sin α = −2/5, 3π/2 < α < 2π, trova cos α. Autocontrollo PDF: √21 / 5."],
          ]),
        },
        {
          id: "ma-p4",
          title: "Dal file allegato, pagina 4: colonna di sinistra.",
          files: [F.maPdf],
          alerts: [A.due14],
          req: "Colonna sinistra: calcola tan α (176–178); verifica le identità 229–231; semplifica 292–295, 143–145, 12–15.",
          children: items("ma", [
            [176, "tan α, sin=4/5", "Calcola tan α, dato sin α = 4/5 e π/2 < α < π. Autocontrollo PDF: −4/3."],
            [177, "tan α, cos=−8/17", "Calcola tan α, dato cos α = −8/17 e π/2 < α < π. Autocontrollo PDF: −15/8."],
            [178, "tan α, cos=−5/6", "Calcola tan α, dato cos α = −5/6 e π < α < 3π/2. Autocontrollo PDF: √11 / 5."],
            [229, "Identità", "Verifica: sin α · cos² α + sin³ α = sin α."],
            [230, "Identità", "Verifica: (1 + tan² α)(1 − sin² α) = 1."],
            [231, "Identità", "Verifica: 1 + tan² α − (1/sin² α) tan² α + 1/cos² α = 1/cos² α.\nConfronta col PDF: la formula è scritta a mano/stampa."],
            [292, "Semplifica", "cos(3π/2 − α) sin(3π/2 + α) + cos(3π/2 + α) sin(3π/2 − α).\nAutocontrollo PDF: 0."],
            [293, "Semplifica", "sin(3π/2 − α) cos α + cos(3π/2 + α) cos(3π/2 − α) + cot(3π/2 − α).\nAutocontrollo PDF: −1 + tan α."],
            [294, "Semplifica", "2 tan(3π/2 + α) cot(3π/2 − α) + sin²(3π/2 + α) + cos²(3π/2 − α).\nAutocontrollo PDF: −1."],
            [295, "Semplifica", "sin(3π/2 + α) + cos(3π/2 − α) + cos(−α) + 2 cos(3π/2 + α).\nAutocontrollo PDF: sin α."],
            [143, "Semplifica", "tan(α/2) sin 2α + 2 cos² α.\nAutocontrollo PDF: 2 cos α."],
            [144, "Semplifica", "tan(π/4 − α) tan(α + π/4) + cos 2α.\nAutocontrollo PDF: 2 cos² α."],
            [145, "Semplifica", "sin²(α/2) + 2 cos²(α/2) − 2 cos²(π/6).\nAutocontrollo PDF: (cos α)/2."],
            [12, "Semplifica", "cos(α − 2π/3) + (1/2) sin α + cos(α − 7π/6) − sin(α − π/6).\nAutocontrollo PDF: −(√3/2) cos α."],
            [13, "Semplifica", "sin(−α) cos(α + 60°) + (1/4) sin 2α + (√3/2) cos² α.\nAutocontrollo PDF: √3 / 2."],
            [14, "Semplifica", "sin²(α + π/4) − sin 2α − (1 − 2 cos²(α/2)) sin α.\nAutocontrollo PDF: 1/2."],
            [15, "Semplifica", "tan(α/2) [cos 2π + sin(π/2 + α)] + sin 2α / cos(π + α).\nAutocontrollo PDF: −sin α."],
          ]),
        },
        {
          id: "ma-p5",
          title: "Dal file allegato, pagina 5: sezione «per tutti».",
          files: [F.maPdf],
          alerts: [A.due14],
          req: "Per tutti: risolvi le equazioni goniometriche 308–317 (k ∈ ℤ) e i problemi sui triangoli rettangoli 55–56. NON fare 329–336 (solo debito).",
          children: items("ma", [
            [308, "tan²(x+π/3) − 3 = 0", "Risolvi, k ∈ ℤ. Autocontrollo PDF: kπ ; π/3 + kπ."],
            [309, "2 cos² 6x − 1 = 0", "Risolvi. Autocontrollo PDF: ±π/24 + kπ/3 ; ±π/8 + kπ/3."],
            [310, "2 sin x cos² x − sin x = 0", "Risolvi. Autocontrollo PDF: kπ ; π/4 + kπ/2."],
            [311, "sin x − √3 cos x = −2", "Risolvi. Autocontrollo PDF: 11π/6 + 2kπ."],
            [312, "2 sin² x = sin 2x", "Risolvi. Autocontrollo PDF: kπ ; π/4 + kπ."],
            [313, "8 sin(π/2−x) − 1 = 4 sin² x", "Risolvi. Autocontrollo PDF: ±π/3 + 2kπ."],
            [314, "sin x − (√2−1) cos x = 0", "Risolvi. Autocontrollo PDF: π/8 + kπ."],
            [315, "cos² x − 3 cos x + 2 = 0", "Risolvi. Autocontrollo PDF: 2kπ."],
            [316, "2 sin² x + 3 sin x − 2 = 0", "Risolvi. Autocontrollo PDF: π/6 + 2kπ ; 5π/6 + 2kπ."],
            [317, "4 sin²(x+π/6) = 3", "Risolvi. Autocontrollo PDF: π/6 + kπ ; π/2 + kπ."],
            [55, "Triangolo rettangolo 5 cm, 4 cm", "Ipotenusa 5 cm, un cateto 4 cm. Ampiezza degli angoli acuti. Autocontrollo PDF: α ≈ 53,1° ; β ≈ 36,9°."],
            [56, "Triangolo rettangolo cateti 7 e 13", "Cateti 7 cm e 13 cm. Ampiezza degli angoli acuti. Autocontrollo PDF: α ≈ 28,3° ; β ≈ 61,7°."],
          ]),
        },
        {
          id: "ma-p6",
          title: "Dal file allegato, pagina 6: sezione «per tutti».",
          hint: "41–46: usa le figure del PDF.",
          files: [F.maPdf],
          alerts: [A.due14],
          req: "Per tutti. NON fare le equazioni 337–344 (blocco debito).\nRisolvi il triangolo ABC, rettangolo in C. Primo teorema: cateto = ipotenusa · sen(angolo opposto) = ipotenusa · cos(angolo adiacente). α in A, β in B, γ = 90° in C; a opposto ad A, b opposto a B, c ipotenusa.\n41–46: misure sui disegni a pagina 6 del PDF.",
          children: items("ma", [
            [16, "b=15, α=30°", "Risolvi ABC, rettangolo in C. Autocontrollo PDF: c = 10√3 ; a = 5√3 ; β = 60°."],
            [17, "c=24, β=60°", "Risolvi. Autocontrollo PDF: b = 12√3 ; a = 12 ; α = 30°."],
            [18, "b=8, a=8√3", "Risolvi. Autocontrollo PDF: c = 16 ; β = 30° ; α = 60°."],
            [19, "c=48, b=24", "Risolvi. Autocontrollo PDF: a = 24√3 ; β = 30° ; α = 60°."],
            [20, "b=22, α=45°", "Risolvi. Autocontrollo PDF: c = 22√2 ; a = 22 ; β = 45°."],
            [21, "c=28, α=45°", "Risolvi. Autocontrollo PDF: b = 14√2 ; a = 14√2 ; β = 45°."],
            [22, "c=26, b=10", "Risolvi. Autocontrollo PDF: a = 24 ; β ≈ 23° ; α ≈ 67°."],
            [41, "Figura c=48, a=25", "Dai disegni nel PDF: c = 48, cateto verticale a = 25. Autocontrollo PDF: b ≈ 41 ; β ≈ 59° ; α ≈ 31°."],
            [42, "Figura a=20, β=π/4", "Cateto verticale a = 20, angolo in B = π/4. Autocontrollo PDF: α = π/4 ; c = 20√2."],
            [43, "Figura c=28, sin β=3/4", "c = 28, sin β = 3/4. Autocontrollo PDF: b = 21 ; a = 7√7 ; α ≈ 41°."],
            [44, "Figura a=28, cos α=3/5", "Cateto verticale a = 28, cos α = 3/5. Autocontrollo PDF: c = 35 ; b = 21 ; β ≈ 37°."],
            [45, "Figura BC=72, AC=30", "BC = 72, AC = 30. Autocontrollo PDF: c = 78 ; β ≈ 23° ; α ≈ 67°."],
            [46, "Figura AC=64, β=arcsin(8/17)", "AC = 64, angolo in B = arcsin(8/17). Autocontrollo PDF: c = 136 ; a = 120 ; α ≈ 62°."],
          ]),
        },
        {
          id: "ma-consegna",
          title: "esercizi per le vacanze — consegna 14 settembre ore 08:00.",
          files: [F.maPdf],
          alerts: [A.due14],
          req: "Compito Classroom «esercizi per le vacanze», 100 punti. Scadenza: 14 settembre 2026, ore 08:00. Svolgi il procedimento, non copiare solo i risultati blu.",
        },
      ],
    },
    {
      id: "zh",
      name: "Cinese",
      teacher: "Di Vincenzo + Zu",
      who: "i prof",
      blurb: "4 testi × 3–4 volte, in cinese. Zu: testo sulle vacanze + dettato + 2 righe/giorno fino al 12 settembre.",
      due: "12 set (caratteri)",
      dueDate: "2026-09-12",
      alerts: [A.due12, A.oralZh, A.dictZu],
      ask: "Due prof, due lavori. Messaggio Di Vincenzo da far girare dai rappresentanti; commentare «ricevuto».\n\nDI VINCENZO (testo integrale):\n«Vi invio due podcast e due letture. I podcast hanno anche la versione scritta che potete consultare, mentre le letture hanno pop up su ogni carattere che mostra la traduzione delle parole, potete scoprire il pinyin e la traduzione in inglese.\nL’obiettivo non è sapere di cosa parlano questi contenuti, ma ascoltare e leggere in cinese per migliorare il vostro livello, quindi fatelo con questa consapevolezza. Al rientro dalle vacanze vi chiederò di riassumere in cinese i contenuti sia dei podcast che dei testi e vi chiederò delle opinioni al riguardo (mi baserò sulle domande fatte dal conduttore alla fine delle puntate per quanto riguarda i podcast). Quindi preparatevi sulla parte in cinese, facendo glossari, riassunti e provando a ripetere i contenuti (usando il lessico che avete già e aggiungendo lessico nuovo che avrete imparato dalla lettura e dall’ascolto di questi testi). Per raggiungere l’obiettivo sarà necessario ascoltare e leggere almeno 3-4 volte i podcast e i testi.\nOltre a ciò, aprire il file del programma svolto e ripassare tutti i caratteri studiati lo scorso anno (Unità 7 vol. 2 e le letture del vol. 3). La prof. Zu farà il dettato al rientro.»\n\nZU: fare il testo sulle vacanze in cinese; 2 righe di caratteri al giorno dall’ultima firma sul quaderno fino al 12 settembre (compreso il recupero da marzo/aprile, non solo da oggi); dettato al rientro.",
      tasks: [
        {
          id: "zh-mianzi",
          title: "Podcast 面子文化 — ascoltare e leggere almeno 3–4 volte; glossario, riassunto e opinione in cinese.",
          who: "Di Vincenzo",
          href: "https://teatimechinese.com/podcast/chinese/22-the-face-culture-in-china",
          alerts: [A.oralZh],
          req: "第22集：中国的“面子文化” (Beginner, 15:24). C’è il transcript sul sito.\n\nObiettivo: ascoltare in cinese, non solo «sapere di cosa parla». Almeno 3–4 volte.\nDa preparare in cinese: glossario (carattere + pinyin + significato) + riassunto + opinione.\nAl rientro Di Vincenzo chiederà riassunto e opinioni; per i podcast userà le domande del conduttore in fondo alla puntata.\nTemi da tenere pronti: 什么是面子？什么时候有面子 / 没面子？你觉得面子重要吗？",
        },
        {
          id: "zh-zhiyin",
          title: "Podcast 知音 — ascoltare e leggere almeno 3–4 volte; glossario, riassunto e risposte alle domande del conduttore.",
          who: "Di Vincenzo",
          href: "https://teatimechinese.com/podcast/chinese/18-do-you-have-a-best-buddy",
          alerts: [A.oralZh],
          req: "第18集：你有知音吗？ (Intermediate, 11:22). 知音 = un amico che ti capisce davvero (storia di 伯牙 e 钟子期).\n\nAlmeno 3–4 ascolti + transcript + glossario + riassunto in cinese.\nDomande del conduttore (fine puntata) — Di Vincenzo si baserà su queste; prepara le risposte in cinese:\n• 你有一个非常非常好的朋友吗？你有一个真正明白你的朋友吗？\n• 你有知音吗？如果有，你们是怎么认识的？你们已经认识多久了？\n• 如果你没有知音：你觉得知音很难找到吗？你觉得有一个知音是一件很重要的事情吗？",
        },
        {
          id: "zh-shuo",
          title: "Lettura 说谎对不对？ — leggere almeno 3–4 volte; glossario, riassunto e opinione in cinese.",
          who: "Di Vincenzo",
          href: "https://chinesereadingpractice.com/2026/05/01/essay-%E8%AF%B4%E8%B0%8E%E5%AF%B9%E4%B8%8D%E5%AF%B9%EF%BC%9F-is-lying-right-or-wrong/",
          alerts: [A.oralZh],
          req: "说谎对不对？ (Intermediate). Saggio: mentire è sempre sbagliato? 善意的谎言; esempio WWII. Popup su ogni carattere (pinyin + inglese).\n\nLeggere almeno 3–4 volte. In cinese: glossario + riassunto + opinione (说谎永远不对吗？善意的谎言可以吗？).\nVocabolario chiave: 说谎 shuōhuǎng, 善意 shànyì, 谎言 huǎngyán, 诚实 chéngshí.",
        },
        {
          id: "zh-wu",
          title: "Lettura 武则天 — leggere almeno 3–4 volte; glossario, riassunto e opinione in cinese.",
          who: "Di Vincenzo",
          href: "https://chinesereadingpractice.com/2026/03/26/%E6%AD%A6%E5%88%99%E5%A4%A9%EF%BC%9A%E4%B8%AD%E5%9B%BD%E5%94%AF%E4%B8%80%E7%9A%84%E5%A5%B3%E7%9A%87%E5%B8%9D-wu-zetian-chinas-only-female-emperor/",
          alerts: [A.oralZh],
          req: "武则天：中国唯一的女皇帝 (Intermediate). Nata nel 624, 皇帝 nel 690, dinastia 周, muore nel 705.\n\nLeggere almeno 3–4 volte. In cinese: glossario + riassunto della vita + opinione (你觉得武则天怎么样？).\nVocabolario chiave: 皇帝 huángdì, 皇后 huánghòu, 权力 quánlì, 统治 tǒngzhì.",
        },
        {
          id: "zh-voce",
          title: "Provando a ripetere i contenuti (usando il lessico che avete già e aggiungendo lessico nuovo).",
          who: "Di Vincenzo",
          alerts: [A.oralZh],
          req: "Dal messaggio: «provando a ripetere i contenuti (usando il lessico che avete già e aggiungendo lessico nuovo)». Non è un file da consegnare: è preparazione per l’orale al rientro (riassunto + opinioni in cinese).",
        },
        {
          id: "zh-prog",
          title: "Aprire il file del programma svolto e ripassare tutti i caratteri studiati lo scorso anno.",
          who: "Di Vincenzo / Zu",
          alerts: [A.dictZu],
          req: "«Aprire il file del programma svolto» (Classroom / materiale della prof) e usarlo per il ripasso caratteri. La Zu farà il dettato al rientro.",
        },
        {
          id: "zh-u7",
          title: "Ripassare tutti i caratteri: Unità 7 volume 2.",
          who: "Zu (indicato da Di Vincenzo)",
          alerts: [A.dictZu],
          req: "Ripassare tutti i caratteri studiati lo scorso anno: Unità 7 del volume 2. Al rientro dettato della prof. Zu.",
        },
        {
          id: "zh-vol3",
          title: "Ripassare tutti i caratteri: letture del volume 3.",
          who: "Zu (indicato da Di Vincenzo)",
          alerts: [A.dictZu],
          req: "Stesso ripasso: tutti i caratteri delle letture del volume 3. Servono per il dettato della Zu.",
        },
        {
          id: "zh-vacanze",
          title: "Fare il testo sulle vacanze in cinese.",
          who: "la Zu",
          alerts: [A.due12],
          req: "Compito della Zu: scrivere un testo in cinese sulle vacanze.\n\nLo scrivi tu, in caratteri, con il lessico che sai (anche quello nuovo dei testi estivi). Non è da far scrivere all’AI. Tienilo pronto per il rientro, insieme alle 2 righe al giorno e al dettato.",
        },
        {
          id: "zh-firma",
          title: "2 righe di caratteri al giorno dall’ultima firma sul quaderno fino al 12 settembre.",
          hint: "Poi usa la scheda Caratteri: 2 righe per ogni giorno fino al 12/09.",
          who: "la Zu",
          alerts: [A.due12],
          req: "Richiesta della Zu: scrivere 2 righe di caratteri cinesi per OGNI giorno, dall’ultimo giorno in cui ha messo la firma sul quaderno (circa marzo/aprile 2026) fino al 12 settembre incluso.\n\nNon è «2 righe in tutto»: è 2 righe × ogni giorno mancante, compreso il recupero. Il giorno successivo alla firma è il primo da fare. Caratteri: Unità 7 vol. 2, letture vol. 3, e/o quelli dei testi estivi.\nApri la scheda Caratteri qui sotto, metti la data della firma, spunta i giorni.",
        },
      ],
    },
  ],
};
