/* Elenco compiti 4ALL linguistico — estate 2026 */
function items(prefix, rows) {
  return rows.map(([num, title]) => ({
    id: prefix + "-" + num,
    title: num + ". " + title,
  }));
}

const DATA = {
  className: "4ALL linguistico",
  school: "Liceo Cairoli — Vigevano",
  subjects: [
    {
      id: "it",
      name: "Italiano",
      blurb: "3 libri + 3 temi (niente AI). Consegna temi a inizio scuola.",
      due: "inizio scuola",
      tasks: [
        { id: "it-calvino", title: "Letto Calvino — Il sentiero dei nidi di ragno", hint: "Scheda già pronta in cartella Italiano. Serve saperne parlare." },
        { id: "it-calvino-oral", title: "So raccontare Calvino (trama, personaggi, stile)" },
        { id: "it-balzano", title: "Letto Balzano — Resto qui" },
        { id: "it-pirandello", title: "Letto Pirandello — Il fu Mattia Pascal" },
        { id: "it-tema-a", title: "Tema tipologia A (A1 o A2) in Word", hint: "Niente AI. Tracce in P000_ORD25.pdf. Lo scrivi tu." },
        { id: "it-tema-b", title: "Tema tipologia B (B1, B2 o B3) in Word", hint: "Niente AI. Lo scrivi tu." },
        { id: "it-tema-c", title: "Tema tipologia C (C1 o C2) in Word", hint: "Niente AI. Lo scrivi tu." },
        { id: "it-consegna", title: "Temi consegnati su Classroom" },
      ],
    },
    {
      id: "en",
      name: "Inglese",
      blurb: "Dickens (Manfredda) + lettorato 100 punti.",
      due: "inizio scuola",
      tasks: [
        { id: "en-dickens-read", title: "Letto A Christmas Carol (Black Cat)" },
        { id: "en-dickens-notes", title: "Appunti Dickens: trama, personaggi, temi", hint: "Scheda già fatta. Copiali sul quaderno.", done: true },
        { id: "en-dickens-oral", title: "So raccontare i 6 capitoli ad alta voce (inglese)" },
        { id: "en-reader", title: "Esercizi del reader Dickens", optional: true },
        { id: "en-106", title: "Performer B2 p. 106 — es. 1–5" },
        { id: "en-108", title: "Performer B2 p. 108 — es. 1" },
        { id: "en-110", title: "Performer B2 p. 110 — es. 1–4" },
        { id: "en-114", title: "Performer B2 p. 114 — es. 3–4" },
        { id: "en-v1", title: "Video 1 + risposte: Why I live a zero waste life", href: "https://www.youtube.com/watch?v=pF72px2R3Hg" },
        { id: "en-v2", title: "Video 2 + risposte: The Simple Solution to Fast Fashion", href: "https://www.youtube.com/watch?v=Bh8dnw67rE0" },
        { id: "en-consegna", title: "Lettorato consegnato su Classroom" },
      ],
    },
    {
      id: "es",
      name: "Spagnolo",
      blurb: "Sepúlveda: due storie. In chat risulta solo la lettura.",
      due: "inizio scuola",
      tasks: [
        { id: "es-diario", title: "Letto Diario de un killer sentimental" },
        { id: "es-yacare", title: "Letto Yacaré" },
        { id: "es-notes", title: "Appunti: trama, personaggi, temi", hint: "Scheda già fatta, in spagnolo semplice.", done: true },
        { id: "es-oral", title: "So raccontare le 12 sezioni ad alta voce (spagnolo)" },
      ],
    },
    {
      id: "ar",
      name: "Storia dell’arte",
      blurb: "Niente consegna. Libro a piacere.",
      due: "inizio scuola",
      tasks: [
        { id: "ar-spaggiari", title: "Riletto il programma svolto su Spaggiari" },
        { id: "ar-libro", title: "Letto Lomartire — La dama e il Moro", optional: true, hint: "Lettura consigliata, non obbligatoria." },
      ],
    },
    {
      id: "fi",
      name: "Fisica",
      blurb: "Maccagnola — 100 punti. Consegna 14 settembre ore 08:00. Solo esercizi in nero (niente debito).",
      due: "14 set 08:00",
      dueDate: "2026-09-14",
      tasks: [
        { id: "fi-teoria", title: "Ripassata la teoria di quarta" },
        { id: "fi-colori", title: "Controllato nel PDF quali esercizi sono in nero" },
        {
          id: "fi-neri",
          title: "Svolti gli esercizi in nero",
          hint: "Spunta sotto solo quelli neri del PDF. Gli evidenziati non ti spettano.",
          children: items("fi", [
            [1, "Cubo sotto vuoto — forza sul coperchio"],
            [2, "Ciaspole sulla neve — pressione"],
            [3, "Torchio idraulico — auto 1600 kg"],
            [4, "Barometro su altro pianeta"],
            [5, "Idroboot 5 km — forza sulla lente"],
            [6, "Sommergibile 1200 kPa — profondità"],
            [7, "Satellite cilindrico — L e I"],
            [8, "ISS — astronauta e casse"],
            [9, "Satellite — nuovo momento d’inerzia"],
            [10, "Ciclista pista circolare — periodo"],
            [11, "Sfera da 3,8 m — velocità al suolo"],
            [12, "Pendolo 8 kg — periodo e energia"],
            [13, "Scivolo con cunetta (figura)"],
            [14, "Skypass Alpe di Siusi — lavoro"],
            [15, "Treno e molle in stazione"],
            [16, "Pistola giocattolo — molla"],
            [17, "Trampolino da sci — gittata"],
            [18, "Auto al passo alpino — lavoro"],
            [19, "g su un pianeta"],
            [20, "Sistema binario — distanza"],
            [21, "Titano — orbita e fuga"],
            [22, "Navicella Encelado → Rea"],
            [23, "Forza Terra–Venere"],
            [24, "Ganimede — periodo e fuga"],
            [25, "Titano 5580 m/s — massa di Saturno"],
            [26, "Auto e autovelox — forza frenante"],
            [27, "Corpo celeste — g, fuga, orbita"],
            [28, "Sole e Adara — attrazione"],
            [29, "Raggio buco nero"],
            [30, "Vostok Strelka e Bielka"],
            [31, "Palla e molla verticale"],
            [32, "Montagne russe (figura)"],
            [33, "Doppler ambulanza"],
            [34, "Impulso sonoro — due uditori"],
            [35, "Martello pneumatico — distanze"],
            [36, "Botto 1600 W a 600 m"],
            [37, "Fischietto per cani 32 kHz"],
            [38, "Rifrazione n=1,46 → 1,21"],
            [39, "Due aerei — Doppler"],
            [40, "Sorgente 40 W a 1 km"],
            [41, "Sirena carabinieri 5000 Hz"],
            [42, "Sorgente 50 W a 500 m"],
            [43, "52 dB a 10 m — potenza"],
            [44, "Onda sismica — velocità"],
            [45, "Specchio concavo e candela"],
            [46, "800 W a 30 km"],
            [47, "Onda EM 2,16×10¹⁵ Hz"],
            [48, "Onda 740 nm in un materiale"],
          ]),
        },
        { id: "fi-evidenziati", title: "Esercizi evidenziati (debito / sufficienza con aiuto)", optional: true, hint: "Non ti spettano: niente debito." },
        { id: "fi-balbi", title: "Letto Balbi — Cercatori di meraviglia" },
        { id: "fi-relazione", title: "Scritta la piccola relazione sul libro", hint: "La scrivi tu. Consegna insieme al lavoro estivo." },
        { id: "fi-consegna", title: "Consegnato il lavoro su Classroom" },
      ],
    },
    {
      id: "ma",
      name: "Matematica",
      blurb: "Maccagnola — 100 punti. Consegna 14 settembre ore 08:00. Solo colonna sinistra / per tutti.",
      due: "14 set 08:00",
      dueDate: "2026-09-14",
      tasks: [
        { id: "ma-teoria", title: "Ripassata la teoria (goniometria, trigo, exp, log)" },
        {
          id: "ma-p1",
          title: "Pag. 1 — grafici 42–44 + problemi 102 e 103",
          children: items("ma", [
            [42, "Grafico esponenziale decrescente"],
            [43, "Grafico esponenziale crescente"],
            [44, "Grafico esponenziale decrescente"],
            ["102a", "Piegare all’infinito — area"],
            ["102b", "Piegare all’infinito — spessore"],
            ["102c", "Piegare 20 volte vs Big Ben"],
            ["103a", "Larve infette — tabella e grafico"],
            ["103b", "Larve — confronto k=0,5"],
          ]),
        },
        {
          id: "ma-p2",
          title: "Pag. 2 — eq. 160–170, diseq. 267–272, log 101–106",
          children: items("ma", [
            [160, "4^x = 2^x − 2"],
            [161, "8 + 2^{x+1} = 2^{2x}"],
            [162, "9^x − 3 = 2 · 3^x"],
            [163, "3^{2x} − 9·3^x + 3 = (1/3)·3^x"],
            [164, "5^{2x} − 5^x = 5^{x−2} − 1/25"],
            [165, "2/(3^x − 1) = 1/(3^x − 5)"],
            [166, "2^x + 8 = 1/4 + 2^{1−x}"],
            [167, "10^x + 10^{2−x} = 101"],
            [168, "9^x + 9 = 10 · 3^x"],
            [169, "2^{x+3} + 4^{x+1} = 320"],
            [170, "2^{x+1} + 2^{3−x} = 17"],
            [267, "(1/3)^{x²+x} < 1/9"],
            [268, "e^x · e^{x−3} ≥ √e"],
            [269, "e^{x²−6} · e^x < 1"],
            [270, "(2^x − 4)/(1 − 3^x) > 0"],
            [271, "(4 − 8^x)/(3^x + 9) ≤ 0"],
            [272, "45 · 2^{2x−2} < −35 · 4^{x−1}"],
            [101, "2 log(x²−1) − log(x+1) − log(x−1)"],
            [102, "(1/2) log₃ x + 2 log₃(x+1) − log₃ 7"],
            [103, "(1/2)(log 7 + log x − log 3) + log √(3x)"],
            [104, "log(x−1)+log(x−2)−log(x+3)"],
            [105, "(1/2)[log₂ a + 2 log₂(a+4)] − log₂(a−1)"],
            [106, "log₂(x+1)+5 log₂(x−1)−4 log₂(x²−1)"],
          ]),
        },
        {
          id: "ma-p3",
          title: "Pag. 3 — 281–290, 373–376, goniometria 123–125 e 131–134",
          children: items("ma", [
            [281, "log₂ x = −5"],
            [282, "log₄(x+2) = 2"],
            [283, "log₅(x² − 4) = 1"],
            [284, "log₂(2x−1) = log₂(x+3)"],
            [285, "log₃(x+1) + 2 log₃ 2 = log₃(x+7)"],
            [286, "log(x−2) + log 5 = log x"],
            [287, "5 log² x − log x = 0"],
            [288, "ln² x − 9 = 0"],
            [289, "log_x 3 = 1/3"],
            [290, "ln((x−4)/(2x+1)) = 0"],
            [373, "log₄(x−1) ≤ −2"],
            [374, "log_{1/3}(1−2x) < 1"],
            [375, "log_{1/2}(x+3) < −1"],
            [376, "log(x²+17x+16) < 2"],
            [123, "Valore goniometrico"],
            [124, "Valore goniometrico"],
            [125, "Valore goniometrico"],
            [131, "sin α=7/25 → cos α"],
            [132, "cos α=−4/5 → sin α"],
            [133, "sin α=1/3 → cos α"],
            [134, "sin α=−2/5 → cos α"],
          ]),
        },
        {
          id: "ma-p4",
          title: "Pag. 4 — tan, identità, semplificazioni",
          children: items("ma", [
            [176, "tan α, sin=4/5"],
            [177, "tan α, cos=−8/17"],
            [178, "tan α, cos=−5/6"],
            [229, "Identità"],
            [230, "Identità"],
            [231, "Identità"],
            [292, "Semplifica"],
            [293, "Semplifica"],
            [294, "Semplifica"],
            [295, "Semplifica"],
            [143, "Semplifica"],
            [144, "Semplifica"],
            [145, "Semplifica"],
            [12, "Semplifica"],
            [13, "Semplifica"],
            [14, "Semplifica"],
            [15, "Semplifica"],
          ]),
        },
        {
          id: "ma-p5",
          title: "Pag. 5 — eq. 308–317, problemi 55–56",
          children: items("ma", [
            [308, "tan²(x+π/3) − 3 = 0"],
            [309, "2 cos² 6x − 1 = 0"],
            [310, "2 sin x cos² x − sin x = 0"],
            [311, "sin x − √3 cos x = −2"],
            [312, "2 sin² x = sin 2x"],
            [313, "8 sin(π/2−x) − 1 = 4 sin² x"],
            [314, "sin x − (√2−1) cos x = 0"],
            [315, "cos² x − 3 cos x + 2 = 0"],
            [316, "2 sin² x + 3 sin x − 2 = 0"],
            [317, "4 sin²(x+π/6) = 3"],
            [55, "Triangolo rettangolo 5 cm, 4 cm"],
            [56, "Triangolo rettangolo cateti 7 e 13"],
          ]),
        },
        {
          id: "ma-p6",
          title: "Pag. 6 — triangoli 16–22 e 41–46",
          hint: "41–46: usa le figure del PDF.",
          children: items("ma", [
            [16, "b=15, α=30°"],
            [17, "c=24, β=60°"],
            [18, "b=8, a=8√3"],
            [19, "c=48, b=24"],
            [20, "b=22, α=45°"],
            [21, "c=28, α=45°"],
            [22, "c=26, b=10"],
            [41, "Figura c=48, a=25"],
            [42, "Figura a=20, β=π/4"],
            [43, "Figura c=28, sin β=3/4"],
            [44, "Figura a=28, cos α=3/5"],
            [45, "Figura BC=72, AC=30"],
            [46, "Figura AC=64, β=arcsin(8/17)"],
          ]),
        },
        { id: "ma-consegna", title: "Consegnato su Classroom" },
      ],
    },
    {
      id: "zh",
      name: "Cinese",
      blurb: "Di Vincenzo: 4 testi × 3–4 volte, in cinese. Zu: dettato + 2 righe/giorno fino al 12 settembre.",
      due: "12 set (caratteri)",
      dueDate: "2026-09-12",
      tasks: [
        { id: "zh-mianzi", title: "Podcast 面子 — 3–4 volte + glossario + riassunto + opinione", href: "https://teatimechinese.com/podcast/chinese/22-the-face-culture-in-china" },
        { id: "zh-zhiyin", title: "Podcast 知音 — 3–4 volte + glossario + riassunto + domande", href: "https://teatimechinese.com/podcast/chinese/18-do-you-have-a-best-buddy" },
        { id: "zh-shuo", title: "Lettura 说谎对不对 — 3–4 volte + glossario + riassunto + opinione", href: "https://chinesereadingpractice.com/2026/05/01/essay-说谎对不对？-is-lying-right-or-wrong/" },
        { id: "zh-wu", title: "Lettura 武则天 — 3–4 volte + glossario + riassunto + opinione", href: "https://chinesereadingpractice.com/2026/03/26/武则天：中国唯一的女皇帝-wu-zetian-chinas-only-female-emperor/" },
        { id: "zh-voce", title: "Ripetuti a voce i 4 contenuti" },
        { id: "zh-prog", title: "Aperto il programma svolto" },
        { id: "zh-u7", title: "Ripassati i caratteri Unità 7 vol. 2" },
        { id: "zh-vol3", title: "Ripassati i caratteri delle letture vol. 3" },
        { id: "zh-firma", title: "Trovata l’ultima firma della Zu sul quaderno", hint: "Poi usa la scheda Caratteri: 2 righe per ogni giorno fino al 12/09." },
      ],
    },
  ],
};
